import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
    page: {
        flex: 1,
        overflow: "auto",
        minHeight: 0,
        background: "#0a0a0a",
        color: "#fff",
        padding: "24px 20px 16px",
        display: "flex",
        flexDirection: "column",
        gap: 16,
        WebkitUserSelect: "none",
        userSelect: "none",
    },
    header: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
    },
    title: {
        fontSize: 22,
        fontWeight: 300,
        letterSpacing: "0.04em",
        color: "#fff",
    },
    addButton: {
        background: "transparent",
        border: "1px solid #333",
        color: "#888",
        borderRadius: 6,
        padding: "8px 16px",
        fontSize: 14,
        cursor: "pointer",
        touchAction: "manipulation",
    },
    reminderRow: {
        display: "flex",
        alignItems: "center",
        gap: 12,
        padding: "12px 14px",
        border: "1px solid #1a1a1a",
        borderRadius: 8,
    },
    reminderDot: {
        width: 8,
        height: 8,
        borderRadius: "50%",
        flexShrink: 0,
    },
    reminderTitle: {
        flex: 1,
        fontSize: 15,
        color: "#ddd",
    },
    reminderTitleDone: {
        flex: 1,
        fontSize: 15,
        color: "#444",
        textDecoration: "line-through",
    },
    reminderDue: {
        fontSize: 12,
        color: "#555",
    },
    actionButton: {
        background: "transparent",
        border: "1px solid #222",
        color: "#555",
        borderRadius: 4,
        padding: "4px 10px",
        fontSize: 12,
        cursor: "pointer",
        touchAction: "manipulation",
    },
    statusBadge: {
        fontSize: 10,
        fontWeight: 700,
        letterSpacing: "0.08em",
        textTransform: "uppercase",
        padding: "2px 6px",
        borderRadius: 4,
    },
    emptyText: {
        fontSize: 13,
        color: "#333",
        fontStyle: "italic",
        paddingTop: 8,
    },
    errorText: {
        fontSize: 13,
        color: "#ef4444",
    },
    addForm: {
        display: "flex",
        flexDirection: "column",
        gap: 10,
        padding: "14px",
        border: "1px solid #222",
        borderRadius: 8,
        background: "#111",
    },
    input: {
        background: "#0a0a0a",
        border: "1px solid #333",
        borderRadius: 6,
        color: "#fff",
        fontSize: 15,
        padding: "10px 12px",
        outline: "none",
        width: "100%",
        boxSizing: "border-box",
    },
    formButtons: {
        display: "flex",
        gap: 8,
    },
    saveButton: {
        flex: 1,
        background: "#fff",
        border: "none",
        color: "#000",
        borderRadius: 6,
        padding: "10px",
        fontSize: 14,
        fontWeight: 600,
        cursor: "pointer",
        touchAction: "manipulation",
    },
    cancelButton: {
        flex: 1,
        background: "transparent",
        border: "1px solid #333",
        color: "#888",
        borderRadius: 6,
        padding: "10px",
        fontSize: 14,
        cursor: "pointer",
        touchAction: "manipulation",
    },
};
