import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
    page: {
        flex: 1,
        overflow: "auto",
        background: "#0a0a0a",
        color: "#fff",
        padding: "20px 16px 12px",
        display: "flex",
        flexDirection: "column",
        gap: 16,
        WebkitUserSelect: "none",
        userSelect: "none",
    },
    title: {
        fontSize: 22,
        fontWeight: 300,
        letterSpacing: "0.04em",
        color: "#fff",
        marginBottom: 4,
    },
    monthRow: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 8,
    },
    monthLabel: {
        fontSize: 16,
        fontWeight: 500,
        color: "#fff",
    },
    navButton: {
        background: "transparent",
        border: "1px solid #333",
        color: "#888",
        borderRadius: 6,
        padding: "6px 14px",
        fontSize: 16,
        cursor: "pointer",
        touchAction: "manipulation",
    },
    dayGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(7, 1fr)",
        gap: 2,
    },
    dayHeader: {
        textAlign: "center",
        fontSize: 11,
        fontWeight: 700,
        color: "#444",
        letterSpacing: "0.08em",
        textTransform: "uppercase",
        padding: "4px 0",
    },
    dayCell: {
        textAlign: "center",
        padding: "10px 4px",
        borderRadius: 6,
        fontSize: 20,
        cursor: "pointer",
        color: "#a7a7a7",
        touchAction: "manipulation",
    },
    dayCellToday: {
        background: "#fff",
        color: "#000",
        fontWeight: 700,
    },
    dayCellSelected: {
        background: "#222",
        color: "#fff",
    },
    dayCellHasEvent: {
        position: "relative",
    },
    eventList: {
        display: "flex",
        flexDirection: "column",
        gap: 8,
        marginTop: 4,
    },
    eventRow: {
        display: "flex",
        alignItems: "center",
        gap: 10,
        padding: "10px 12px",
        border: "1px solid #1e1e1e",
        borderRadius: 8,
    },
    eventDot: {
        width: 6,
        height: 6,
        borderRadius: "50%",
        flexShrink: 0,
    },
    eventTime: {
        fontSize: 13,
        color: "#555",
        minWidth: 40,
    },
    eventTitle: {
        fontSize: 14,
        color: "#ddd",
        flex: 1,
    },
    emptyText: {
        fontSize: 13,
        color: "#333",
        fontStyle: "italic",
        paddingTop: 8,
    },
    sectionLabel: {
        fontSize: 11,
        fontWeight: 700,
        letterSpacing: "0.12em",
        textTransform: "uppercase",
        color: "#444",
        marginBottom: 4,
    },
    errorText: {
        fontSize: 13,
        color: "#ef4444",
    },
    modalOverlay: {
        position: "fixed",
        inset: 0,
        zIndex: 100,
        background: "rgba(0,0,0,0.75)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: 16,
    },
    modal: {
        background: "#111",
        border: "1px solid #222",
        borderRadius: 12,
        padding: "20px 16px",
        width: "100%",
        maxWidth: 400,
        display: "flex",
        flexDirection: "column",
        gap: 12,
    },
    modalTitle: {
        fontSize: 16,
        fontWeight: 600,
        color: "#fff",
        marginBottom: 4,
    },
    modalRow: {
        display: "flex",
        alignItems: "center",
        gap: 10,
        padding: "8px 0",
        borderBottom: "1px solid #1a1a1a",
    },
    actionButton: {
        background: "transparent",
        border: "1px solid #222",
        color: "#555",
        borderRadius: 4,
        padding: "4px 10px",
        fontSize: 12,
        cursor: "pointer",
        touchAction: "manipulation",
    },
    closeButton: {
        marginTop: 4,
        background: "transparent",
        border: "1px solid #333",
        color: "#888",
        borderRadius: 6,
        padding: "10px",
        fontSize: 14,
        cursor: "pointer",
        touchAction: "manipulation",
        width: "100%",
    },
};
